### ISSUE TITLE
OSError: Unable to open file h5py.h5f

### ISSUE THREAD

**Issue by niddal-imam** [kurapan/EAST#10]
I have been able to train the model, but when trying to test the model, I got this error message:
File "/home/paperspace/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file read failed: time = Thu Feb 21 01:07:23 2019

Any suggestion?

**Comment by kurapan** [comment]
Is this the whole error message? I can't really tell exactly at which line in my code it fails. 
Anyway, it should be somewhere where the weights are loaded. I'll have a look at it. Could you possibly tell me what is your version of h5py package?

**Comment by niddal-imam** [comment]
Thanks for your replay. I was able to solve the issues by adding checkpoint's name to the model path. for example, --model_path=tmp/icdar2015_east_resnet50/Models/model-70.h5. However, I got another error message:
F tensorflow/compiler/jit/deadness_analysis.cc:572] Check failed: it != predicate_map_.end() batch_normalization_1/cond/FusedBatchNorm/Switch_1
Aborted

**Comment by kurapan** [comment]
Oh, I see. Yeah, you have to specify the checkpoint in `--model_path`. I'll update the readme file so that it's clear.

**Comment by kalai2033** [comment]
!python eval.py --test_data_path=/content/east/data/test/ --model_path=/content/east/Emodel.h5 --output_dir=/content/east/out/


Im getting the same error when i run the above command. Kindly please help me. PFB the traceback logs.

Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 140, in main
    model.load_weights(FLAGS.model_path)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 18874368, sblock->base_addr = 0, stored_eof = 97433760)

**Comment by Danzo0l** [comment]
> Спасибо за повтор. Мне удалось решить проблемы, добавив имя контрольной точки в путь к модели. например, --model_path = tmp / icdar2015_east_resnet50 / Models / model-70.h5.

Можно подробнее, пожалуйста
