### ISSUE TITLE
Error loading pretrained model.json

### ISSUE THREAD

**Issue by unik00** [kurapan/EAST#23]
Hi. Thank you very much for your EAST implementation in Keras. 
When I download the pretrained model from the link in README and run eval.py, it raised an error. 
  File "eval.py", line 194, in <module>
    main()
  File "eval.py", line 140, in main
    model = model_from_json(loaded_model_json, custom_objects={'tf': tf, 'RESIZE_FACTOR': RESIZE_FACTOR})
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 492, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 687, in call
    return self.function(inputs, **arguments)
  **File "/home/u00012/code/Text-Detection/EAST-keras/model.py"**, line 13, in resize_bilinear
    return tf.image.resize_bilinear(x, size=[K.shape(x)[1]*RESIZE_FACTOR, K.shape(x)[2]*RESIZE_FACTOR])

**Comment by kurapan** [comment]
Does it mention what kind of error?

Could you also tell me what version of Keras (and possibly TF as well) you use?

**Comment by kalai2033** [comment]
!python eval.py --test_data_path=/content/east/data/test/ --model_path=/content/east/model.h5 --output_dir=/content/east/out/

When i try to run the above eval.py cmd, im getting the following error. Im trying to run the pretrained models for my dataset. Please help.

Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 140, in main
    model.load_weights(FLAGS.model_path)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 18874368, sblock->base_addr = 0, stored_eof = 97433760)

**Comment by kurapan** [comment]
Sorry for a late reply.

I'm not exactly sure what the problem might be. If you're still trying to solve the issue, could you first try to downgrade Keras to 2.1.4 and TF to a version between 1.4 and 1.8, and make sure h5py package is version 2.7? But I don't think this is the cause of the problem... It seems like a corrupt file. Have you tried deleting and downloading the weights again?
