### ISSUE TITLE
Getting Error while started training

### ISSUE THREAD

**Issue by smaliaquib** [kurapan/EAST#24]
UserWarning('Using a generator with `use_multiprocessing=True`'
Epoch 1/800
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Aquib\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Aquib\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aquib\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\Aquib\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in <lambda>
    initargs=(seqs, self.random_seed))
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aquib\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

**Comment by kurapan** [comment]
I haven't tested the code on Windows and I have no Windows machine I could try it with.
There seems to be some issue with Python multiprocessing in Windows. You could try rewriting the part of code where the validation dataset is loaded so that it doesn't use multiprocessing and simply just loads the data in one thread. I use multiprocessing just to speed up the process of data loading.

**Comment by smaliaquib** [comment]
Solved by downgrading keras

**Comment by kurapan** [comment]
That's interesting. Good to hear you were able to solve it.
