### ISSUE TITLE
TypeError: can't pickle generator objects

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#51]
I get the following error when setting "use_multiprocessing=True". Why, and how should I solve this?

`
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    main()
  File "train.py", line 260, in main
    history = parallel_model.fit_generator(train_data_generator, epochs=FLAGS.max_epochs, steps_per_epoch=train_samples_count/FLAGS.batch_size, workers=FLAGS.nb_workers, use_multiprocessing=True, max_queue_size=10, callbacks=callbacks, verbose=1)
  File "/home/johan/virtualenvs/east/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/johan/virtualenvs/east/lib/python3.6/site-packages/keras/engine/training.py", line 2176, in fit_generator
    enqueuer.start(workers=workers, max_queue_size=max_queue_size)
  File "/home/johan/virtualenvs/east/lib/python3.6/site-packages/keras/utils/data_utils.py", line 726, in start
    thread.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in _init_
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in _init_
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects
swig/python detected a memory leak of type 'int64_t *', no destructor found.`

**Comment by kurapan** [comment]
I've never seen this error. What versions of Keras and TF do you use?
