### ISSUE TITLE
ValueError: Error when checking input: expected input_image to have 4 dimensions, but got array with shape (0, 1)

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#52]
When running more than 5 epochs i get the error "ValueError: Error when checking input: expected input_image to have 4 dimensions, but got array with shape (0, 1)"
Why?

`
Epoch 1/10
4 training images in /home/ims
2/1 [=============================================] - 69s 35s/step - loss: 0.0168 - pred_score_map_loss: 0.0100 - pred_geo_map_loss: 0.0000e+00
Epoch 2/10
2/1 [=============================================] - 47s 24s/step - loss: 0.0167 - pred_score_map_loss: 0.0100 - pred_geo_map_loss: 0.0000e+00
Epoch 3/10
2/1 [=============================================] - 38s 19s/step - loss: 0.0167 - pred_score_map_loss: 0.0100 - pred_geo_map_loss: 0.0000e+00
Epoch 4/10
2/1 [=============================================] - 37s 19s/step - loss: 0.0166 - pred_score_map_loss: 0.0100 - pred_geo_map_loss: 0.0000e+00
Epoch 5/10
2/1 [=============================================] - 37s 19s/step - loss: 0.0166 - pred_score_map_loss: 0.0100 - pred_geo_map_loss: 0.0000e+00
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jj/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/jj/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 429, in main
    run()
  File "/home/jj/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jjEAST-master/train.py", line 264, in <module>
    main()
  File "/home/jj/EAST-maste/train.py", line 260, in main
    history = parallel_model.fit_generator(train_data_generator, epochs=FLAGS.max_epochs, steps_per_epoch=train_samples_count/FLAGS.batch_size, workers=FLAGS.nb_workers, use_multiprocessing=False, max_queue_size=10, callbacks=callbacks, verbose=1)
  File "/jj/virtualenvs/east_keras/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jj/virtualenvs/east_keras/lib/python3.6/site-packages/keras/engine/training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/jj/Documents/virtualenvs/east_keras/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/jj/Documents//EAST-master/train.py", line 157, in on_epoch_end
    batch_size=FLAGS.batch_size)
  File "/home/jj/Documents/virtualenvs/east_keras/lib/python3.6/site-packages/keras/engine/training.py", line 1768, in evaluate
    batch_size=batch_size)
  File "/home/jj/Documents/virtualenvs/east_keras/lib/python3.6/site-packages/keras/engine/training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "/home/jj/Documents/virtualenvs/east_keras/lib/python3.6/site-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_image to have 4 dimensions, but got array with shape (0, 1)
`

**Comment by kurapan** [comment]
Does this always happen after 5 epochs? Do you use the same images in each epoch? It seems that there's an issue with the input which would suggest that the image isn't correctly loaded or something. I'm not really sure how the data loader can pass something with shape (0, 1), but maybe you can figure out if the image is loaded correctly and processed correctly if you print out the shape of the image after `imread`ing it and after each transformation in `data_processor.py`.

**Comment by jhaggle** [comment]
I figured out that it was because I did not have any validation images. Normally it's optional to use validation images, but in this implementation it is mandatory.
