### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (truediv_4:0) to a numpy array.

### ISSUE THREAD

**Issue by nehasaraf1994** [kurapan/EAST#54]
Hello. While training in the first epoch itself, I keep getting this error:

File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 767, in on_epoch
    yield epoch_logs
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 181, in run_one_epoch
    step += 1
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 789, in on_batch
    self.progbar.on_batch_end(step, batch_logs)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 781, in on_batch_end
    self.progbar.update(self.seen, self.log_values)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 559, in update
    avg = np.mean(self._values[k][0] / max(1, self._values[k][1]))
  File "<__array_function__ internals>", line 6, in mean
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3335, in mean
    out=out, **kwargs)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/_methods.py", line 135, in _mean
    arr = asanyarray(a)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 728, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (truediv_2:0) to a numpy array.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 279, in <module>
    main()
  File "train.py", line 276, in main
    history = parallel_model.fit(train_data_generator, epochs=FLAGS.max_epochs, steps_per_epoch=train_samples_count/FLAGS.batch_size, callbacks=callbacks, verbose=1)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397, in fit
    prefix='val_')
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 772, in on_epoch
    self.progbar.on_epoch_end(epoch, epoch_logs)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 789, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 559, in update
    avg = np.mean(self._values[k][0] / max(1, self._values[k][1]))
  File "<__array_function__ internals>", line 6, in mean
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3335, in mean
    out=out, **kwargs)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/_methods.py", line 135, in _mean
    arr = asanyarray(a)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/nesaraf/Desktop/tf2Env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 728, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (truediv_4:0) to a numpy array.

Not able to figure out why? Please let me know.

**Comment by Benrflanders** [comment]
Hello @nehasaraf1994, were you able to solve this error? I'm having the same error come up. 

I've tried changing verbose output to 0, but end up with the system exiting with code "Killed: 9."
