### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by dohai90** [kurapan/EAST#6]
Thank you for your work.
I faced the following error while training the model:
`Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 246, in main
    history = parallel_model.fit_generator(train_data_generator, epochs=FLAGS.max_epochs, steps_per_epoch=train_samples_count/FLAGS.batch_size, workers=FLAGS.nb_workers, use_multiprocessing=True, max_queue_size=10, callbacks=callbacks, verbose=1)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [4,64,128,128] vs. shape[1] = [4,256,129,129]
         [[Node: concatenate_3/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:@training/AdamW/gradients/concatenate_3/concat_grad/Slice"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](concatenate_3/concat-0-TransposeNHWCToNCHW-LayoutOptimizer, zero_padding2d_1/Pad, loss/pred_geo_map_loss/split_1-0-LayoutOptimizer)]]
         [[Node: loss/pred_score_map_loss/Mean_2/_3637 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_23550_loss/pred_score_map_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

I use Keras 2.2.0 and it displays the warning like this: 
`/usr/local/lib/python3.5/dist-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.`

Is this the cause of this issue?
Best regards.

**Comment by dohai90** [comment]
I have found a solution for this issue. I changed line 51 of model.py from:
`x = concatenate([x, ZeroPadding2D(((1, 0),(1, 0)))(resnet.get_layer('activation_10').output)], axis=3)`
to:
`x = concatenate([x, resnet.get_layer('activation_10').output], axis=3)`
and the issue is resolved.
Best regards.

**Comment by kurapan** [comment]
I had to insert ZeroPadding2D because the ResNet output of one of the layers wasn't exactly a half of the previous resolution, for some weird reason, even though it was divisible by 2. So the ZeroPadding2D was there just to turn 127x127 feature maps into 128x128 feature maps so that you can concat them in the decoder part. I guess they fixed the issue that was causing the wrong behavior of ResNet in the latest Keras release.
