### ISSUE TITLE
error in adamw learning rate

### ISSUE THREAD

**Issue by abhi-84** [kurapan/EAST#63]
Hi there
I am geting following error when training on my custom image data. I have 120 images which I am testing as of now. Will put more images once feasibility check is completed. 

python train.py --gpu_list=0 --input_size=512 --batch_size=10 --nb_workers=6 --training_data_path=new_train_data --validation_data_path=new_val_data --checkpoint_path=test_east_resnet50/ 

Traceback (most recent call last):
  File "train.py", line 256, in <module>
    main()
  File "train.py", line 241, in main
    opt = AdamW(FLAGS.init_learning_rate)
  File "/media/abhi/New Volume/Deep Learning/thermal_scanner/EAST-master/adamw.py", line 31, in __init__
    self.lr = K.variable(lr, name='lr')
AttributeError: can't set attribute

Can you also help me know how to create annotation files automatically so that I can get data in x1,y1,x2,y2,x3,y3,x4,y4 format?

Expecting quick reply
Thanks

**Comment by fantasy995** [comment]
It seems that in the new version of Keras LR has been renamed to Learning_Rate, which is how I changed it.And change the LR for the other places in the code to learning_rate as well.
btw, I want to know if you have run this code successfully so far, because I found problems with the loss function while training my data.

**Comment by fantasy995** [comment]
ok, I've solved my problem.
if the text area in gt file is labeled by ### or * will be ignored during training.
