### ISSUE TITLE
File "/home/u00012/code/Text-Detection/EAST-keras/model.py", line 13, in resize_bilinear 

### ISSUE THREAD

**Issue by Marisamy01** [kurapan/EAST#65]
trying to run eval,py file, it through below errors when it reads data from  model.json file 

  File "/home/u00012/code/Text-Detection/EAST-keras/model.py", line 13, in resize_bilinear
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_bilinear'
tf = 2.0
keras 2.1.5
python 3.7

Traceback (most recent call last):
  File "eval.py", line 201, in <module>
    main()
  File "eval.py", line 145, in main
    model = model_from_json(loaded_model_json, custom_objects={'tf': tf, 'RESIZE_FACTOR': RESIZE_FACTOR})
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 906, in from_config
    config, custom_objects)
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\ELCOT\.conda\envs\mypython3_7\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 795, in call
    return self.function(inputs, **arguments)
  File "/home/u00012/code/Text-Detection/EAST-keras/model.py", line 13, in resize_bilinear
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_bilinear

Thanks in advance

**Comment by kurapan** [comment]
I haven't used the code with TF 2.0. From what I hear, TF 2.0 API is quite different from 1.X so I suppose that `resize_bilinear` was removed from it. Try if it works with a TF 1.x version such as 1.5 for you if you can. If you need to run TF 2.0, you probably have to find where the `resize_bilinear` function or its new alternative is and rewrite that part of the code accordingly.
